### ISSUE TITLE
Login error since last Carelink scheduled maintenance

### ISSUE THREAD

**Issue by ffernandezro** [FredMK/minimed-connect-to-nightscout-wrapper#8]
Hello @FredMK 

First of all, thanks a lot for your incredible work, i've been using it for years!!
Since the maintenance update carried out this afternoon in carelink, i get this error:

pi@raspberryfjfr:~/minimed-connect-to-nightscout-wrapper $ node run.js
Error: Carelink invalid username or password
stack: Error: Carelink invalid username or password
    at doLoginEu3 (/home/pi/minimed-connect-to-nightscout-wrapper/node_modules/minimed-connect-to-nightscout/carelink.js:153:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Do you know about this problem?

With my credentials, the login from carelink home works fine.
Same credentials that i have in  .env file

Thank you again for your valuable help.
BR.

**Comment by adipanait** [comment]
this is also opened here - it may take some time https://github.com/nightscout/minimed-connect-to-nightscout/issues/47

**Comment by FredMK** [comment]
I'm no longer using my sensor or the program, so I won't look into the problem.

In this wrapper I'm using my own fork of the "minimed-connect-to-nightscout" package, so if there will be a fix in that repo, you need to update the package.json file.

**Comment by ffernandezro** [comment]
Thanks for the answer @FredMK 
👍
